// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/cbz_export.dart';
import 'api/download_engine.dart';
import 'api/mangalib_client.dart';
import 'api/models.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DownloadProgress> dco_decode_StreamSink_download_progress_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ListType dco_decode_box_autoadd_list_type(dynamic raw);

  @protected
  MangaDetails dco_decode_box_autoadd_manga_details(dynamic raw);

  @protected
  ReadingPosition dco_decode_box_autoadd_reading_position(dynamic raw);

  @protected
  Chapter dco_decode_chapter(dynamic raw);

  @protected
  ChapterDownloadRequest dco_decode_chapter_download_request(dynamic raw);

  @protected
  ChapterHistory dco_decode_chapter_history(dynamic raw);

  @protected
  ChapterPage dco_decode_chapter_page(dynamic raw);

  @protected
  CommentItem dco_decode_comment_item(dynamic raw);

  @protected
  CommentsData dco_decode_comments_data(dynamic raw);

  @protected
  ConstantItem dco_decode_constant_item(dynamic raw);

  @protected
  ContinueReadingItem dco_decode_continue_reading_item(dynamic raw);

  @protected
  DownloadProgress dco_decode_download_progress(dynamic raw);

  @protected
  DownloadState dco_decode_download_state(dynamic raw);

  @protected
  DownloadedChapterInfo dco_decode_downloaded_chapter_info(dynamic raw);

  @protected
  DownloadedMangaGroup dco_decode_downloaded_manga_group(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Genre dco_decode_genre(dynamic raw);

  @protected
  HomePageData dco_decode_home_page_data(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LibraryEntry dco_decode_library_entry(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw);

  @protected
  List<ChapterDownloadRequest> dco_decode_list_chapter_download_request(
      dynamic raw);

  @protected
  List<ChapterHistory> dco_decode_list_chapter_history(dynamic raw);

  @protected
  List<ChapterPage> dco_decode_list_chapter_page(dynamic raw);

  @protected
  List<CommentItem> dco_decode_list_comment_item(dynamic raw);

  @protected
  List<ConstantItem> dco_decode_list_constant_item(dynamic raw);

  @protected
  List<ContinueReadingItem> dco_decode_list_continue_reading_item(dynamic raw);

  @protected
  List<DownloadedChapterInfo> dco_decode_list_downloaded_chapter_info(
      dynamic raw);

  @protected
  List<DownloadedMangaGroup> dco_decode_list_downloaded_manga_group(
      dynamic raw);

  @protected
  List<Genre> dco_decode_list_genre(dynamic raw);

  @protected
  List<LibraryEntry> dco_decode_list_library_entry(dynamic raw);

  @protected
  List<MangaRelationItem> dco_decode_list_manga_relation_item(dynamic raw);

  @protected
  List<MangaSearchResult> dco_decode_list_manga_search_result(dynamic raw);

  @protected
  List<MangaSimilarItem> dco_decode_list_manga_similar_item(dynamic raw);

  @protected
  List<Person> dco_decode_list_person(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Tag> dco_decode_list_tag(dynamic raw);

  @protected
  ListType dco_decode_list_type(dynamic raw);

  @protected
  MangaConstants dco_decode_manga_constants(dynamic raw);

  @protected
  MangaDetails dco_decode_manga_details(dynamic raw);

  @protected
  MangaRelationItem dco_decode_manga_relation_item(dynamic raw);

  @protected
  MangaSearchResult dco_decode_manga_search_result(dynamic raw);

  @protected
  MangaSimilarItem dco_decode_manga_similar_item(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ListType? dco_decode_opt_box_autoadd_list_type(dynamic raw);

  @protected
  MangaDetails? dco_decode_opt_box_autoadd_manga_details(dynamic raw);

  @protected
  ReadingPosition? dco_decode_opt_box_autoadd_reading_position(dynamic raw);

  @protected
  Person dco_decode_person(dynamic raw);

  @protected
  ReadingPosition dco_decode_reading_position(dynamic raw);

  @protected
  ReadingStreakInfo dco_decode_reading_streak_info(dynamic raw);

  @protected
  Tag dco_decode_tag(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DownloadProgress> sse_decode_StreamSink_download_progress_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ListType sse_decode_box_autoadd_list_type(SseDeserializer deserializer);

  @protected
  MangaDetails sse_decode_box_autoadd_manga_details(
      SseDeserializer deserializer);

  @protected
  ReadingPosition sse_decode_box_autoadd_reading_position(
      SseDeserializer deserializer);

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer);

  @protected
  ChapterDownloadRequest sse_decode_chapter_download_request(
      SseDeserializer deserializer);

  @protected
  ChapterHistory sse_decode_chapter_history(SseDeserializer deserializer);

  @protected
  ChapterPage sse_decode_chapter_page(SseDeserializer deserializer);

  @protected
  CommentItem sse_decode_comment_item(SseDeserializer deserializer);

  @protected
  CommentsData sse_decode_comments_data(SseDeserializer deserializer);

  @protected
  ConstantItem sse_decode_constant_item(SseDeserializer deserializer);

  @protected
  ContinueReadingItem sse_decode_continue_reading_item(
      SseDeserializer deserializer);

  @protected
  DownloadProgress sse_decode_download_progress(SseDeserializer deserializer);

  @protected
  DownloadState sse_decode_download_state(SseDeserializer deserializer);

  @protected
  DownloadedChapterInfo sse_decode_downloaded_chapter_info(
      SseDeserializer deserializer);

  @protected
  DownloadedMangaGroup sse_decode_downloaded_manga_group(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Genre sse_decode_genre(SseDeserializer deserializer);

  @protected
  HomePageData sse_decode_home_page_data(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LibraryEntry sse_decode_library_entry(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer);

  @protected
  List<ChapterDownloadRequest> sse_decode_list_chapter_download_request(
      SseDeserializer deserializer);

  @protected
  List<ChapterHistory> sse_decode_list_chapter_history(
      SseDeserializer deserializer);

  @protected
  List<ChapterPage> sse_decode_list_chapter_page(SseDeserializer deserializer);

  @protected
  List<CommentItem> sse_decode_list_comment_item(SseDeserializer deserializer);

  @protected
  List<ConstantItem> sse_decode_list_constant_item(
      SseDeserializer deserializer);

  @protected
  List<ContinueReadingItem> sse_decode_list_continue_reading_item(
      SseDeserializer deserializer);

  @protected
  List<DownloadedChapterInfo> sse_decode_list_downloaded_chapter_info(
      SseDeserializer deserializer);

  @protected
  List<DownloadedMangaGroup> sse_decode_list_downloaded_manga_group(
      SseDeserializer deserializer);

  @protected
  List<Genre> sse_decode_list_genre(SseDeserializer deserializer);

  @protected
  List<LibraryEntry> sse_decode_list_library_entry(
      SseDeserializer deserializer);

  @protected
  List<MangaRelationItem> sse_decode_list_manga_relation_item(
      SseDeserializer deserializer);

  @protected
  List<MangaSearchResult> sse_decode_list_manga_search_result(
      SseDeserializer deserializer);

  @protected
  List<MangaSimilarItem> sse_decode_list_manga_similar_item(
      SseDeserializer deserializer);

  @protected
  List<Person> sse_decode_list_person(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Tag> sse_decode_list_tag(SseDeserializer deserializer);

  @protected
  ListType sse_decode_list_type(SseDeserializer deserializer);

  @protected
  MangaConstants sse_decode_manga_constants(SseDeserializer deserializer);

  @protected
  MangaDetails sse_decode_manga_details(SseDeserializer deserializer);

  @protected
  MangaRelationItem sse_decode_manga_relation_item(
      SseDeserializer deserializer);

  @protected
  MangaSearchResult sse_decode_manga_search_result(
      SseDeserializer deserializer);

  @protected
  MangaSimilarItem sse_decode_manga_similar_item(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ListType? sse_decode_opt_box_autoadd_list_type(SseDeserializer deserializer);

  @protected
  MangaDetails? sse_decode_opt_box_autoadd_manga_details(
      SseDeserializer deserializer);

  @protected
  ReadingPosition? sse_decode_opt_box_autoadd_reading_position(
      SseDeserializer deserializer);

  @protected
  Person sse_decode_person(SseDeserializer deserializer);

  @protected
  ReadingPosition sse_decode_reading_position(SseDeserializer deserializer);

  @protected
  ReadingStreakInfo sse_decode_reading_streak_info(
      SseDeserializer deserializer);

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_download_progress_Sse(
      RustStreamSink<DownloadProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_list_type(
      ListType self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_manga_details(
      MangaDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_reading_position(
      ReadingPosition self, SseSerializer serializer);

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_download_request(
      ChapterDownloadRequest self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_history(
      ChapterHistory self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_page(ChapterPage self, SseSerializer serializer);

  @protected
  void sse_encode_comment_item(CommentItem self, SseSerializer serializer);

  @protected
  void sse_encode_comments_data(CommentsData self, SseSerializer serializer);

  @protected
  void sse_encode_constant_item(ConstantItem self, SseSerializer serializer);

  @protected
  void sse_encode_continue_reading_item(
      ContinueReadingItem self, SseSerializer serializer);

  @protected
  void sse_encode_download_progress(
      DownloadProgress self, SseSerializer serializer);

  @protected
  void sse_encode_download_state(DownloadState self, SseSerializer serializer);

  @protected
  void sse_encode_downloaded_chapter_info(
      DownloadedChapterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_downloaded_manga_group(
      DownloadedMangaGroup self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_genre(Genre self, SseSerializer serializer);

  @protected
  void sse_encode_home_page_data(HomePageData self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library_entry(LibraryEntry self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_download_request(
      List<ChapterDownloadRequest> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_history(
      List<ChapterHistory> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_page(
      List<ChapterPage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comment_item(
      List<CommentItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_constant_item(
      List<ConstantItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_continue_reading_item(
      List<ContinueReadingItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_downloaded_chapter_info(
      List<DownloadedChapterInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_downloaded_manga_group(
      List<DownloadedMangaGroup> self, SseSerializer serializer);

  @protected
  void sse_encode_list_genre(List<Genre> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_entry(
      List<LibraryEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_manga_relation_item(
      List<MangaRelationItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_manga_search_result(
      List<MangaSearchResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_manga_similar_item(
      List<MangaSimilarItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_person(List<Person> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag(List<Tag> self, SseSerializer serializer);

  @protected
  void sse_encode_list_type(ListType self, SseSerializer serializer);

  @protected
  void sse_encode_manga_constants(
      MangaConstants self, SseSerializer serializer);

  @protected
  void sse_encode_manga_details(MangaDetails self, SseSerializer serializer);

  @protected
  void sse_encode_manga_relation_item(
      MangaRelationItem self, SseSerializer serializer);

  @protected
  void sse_encode_manga_search_result(
      MangaSearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_manga_similar_item(
      MangaSimilarItem self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_list_type(
      ListType? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_manga_details(
      MangaDetails? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_reading_position(
      ReadingPosition? self, SseSerializer serializer);

  @protected
  void sse_encode_person(Person self, SseSerializer serializer);

  @protected
  void sse_encode_reading_position(
      ReadingPosition self, SseSerializer serializer);

  @protected
  void sse_encode_reading_streak_info(
      ReadingStreakInfo self, SseSerializer serializer);

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
