// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void pauseDownloads() =>
    RustLib.instance.api.crateApiDownloadEnginePauseDownloads();

void resumeDownloads() =>
    RustLib.instance.api.crateApiDownloadEngineResumeDownloads();

void cancelDownloads() =>
    RustLib.instance.api.crateApiDownloadEngineCancelDownloads();

Stream<DownloadProgress> startChapterDownload(
        {required String slugUrl,
        required PlatformInt64 mangaId,
        required List<ChapterDownloadRequest> chapters,
        required String appDir,
        required PlatformInt64 concurrentImages}) =>
    RustLib.instance.api.crateApiDownloadEngineStartChapterDownload(
        slugUrl: slugUrl,
        mangaId: mangaId,
        chapters: chapters,
        appDir: appDir,
        concurrentImages: concurrentImages);
