// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class Chapter {
  final PlatformInt64 id;
  final String volume;
  final String number;
  final String? name;
  final PlatformInt64? branchId;
  final PlatformInt64 branchesCount;
  final bool isPaid;

  const Chapter({
    required this.id,
    required this.volume,
    required this.number,
    this.name,
    this.branchId,
    required this.branchesCount,
    required this.isPaid,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      volume.hashCode ^
      number.hashCode ^
      name.hashCode ^
      branchId.hashCode ^
      branchesCount.hashCode ^
      isPaid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chapter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          volume == other.volume &&
          number == other.number &&
          name == other.name &&
          branchId == other.branchId &&
          branchesCount == other.branchesCount &&
          isPaid == other.isPaid;
}

class ChapterDownloadRequest {
  final String volume;
  final String number;
  final PlatformInt64? branchId;

  const ChapterDownloadRequest({
    required this.volume,
    required this.number,
    this.branchId,
  });

  @override
  int get hashCode => volume.hashCode ^ number.hashCode ^ branchId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterDownloadRequest &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          number == other.number &&
          branchId == other.branchId;
}

class ChapterHistory {
  final PlatformInt64 mangaId;
  final String volume;
  final String number;
  final PlatformInt64 pageIndex;
  final PlatformInt64 totalPages;
  final bool isCompleted;
  final String lastReadAt;

  const ChapterHistory({
    required this.mangaId,
    required this.volume,
    required this.number,
    required this.pageIndex,
    required this.totalPages,
    required this.isCompleted,
    required this.lastReadAt,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      volume.hashCode ^
      number.hashCode ^
      pageIndex.hashCode ^
      totalPages.hashCode ^
      isCompleted.hashCode ^
      lastReadAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterHistory &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          volume == other.volume &&
          number == other.number &&
          pageIndex == other.pageIndex &&
          totalPages == other.totalPages &&
          isCompleted == other.isCompleted &&
          lastReadAt == other.lastReadAt;
}

class ChapterPage {
  final String url;
  final PlatformInt64? width;
  final PlatformInt64? height;

  const ChapterPage({
    required this.url,
    this.width,
    this.height,
  });

  @override
  int get hashCode => url.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterPage &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          width == other.width &&
          height == other.height;
}

class CommentItem {
  final PlatformInt64 id;
  final PlatformInt64? rootId;
  final PlatformInt64? parentComment;
  final PlatformInt64 commentLevel;
  final String text;
  final String createdAt;
  final String username;
  final String userAvatar;
  final PlatformInt64 votesUp;
  final PlatformInt64 votesDown;

  const CommentItem({
    required this.id,
    this.rootId,
    this.parentComment,
    required this.commentLevel,
    required this.text,
    required this.createdAt,
    required this.username,
    required this.userAvatar,
    required this.votesUp,
    required this.votesDown,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rootId.hashCode ^
      parentComment.hashCode ^
      commentLevel.hashCode ^
      text.hashCode ^
      createdAt.hashCode ^
      username.hashCode ^
      userAvatar.hashCode ^
      votesUp.hashCode ^
      votesDown.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rootId == other.rootId &&
          parentComment == other.parentComment &&
          commentLevel == other.commentLevel &&
          text == other.text &&
          createdAt == other.createdAt &&
          username == other.username &&
          userAvatar == other.userAvatar &&
          votesUp == other.votesUp &&
          votesDown == other.votesDown;
}

class CommentsData {
  final List<CommentItem> root;
  final List<CommentItem> replies;
  final bool hasNextPage;
  final PlatformInt64 page;

  const CommentsData({
    required this.root,
    required this.replies,
    required this.hasNextPage,
    required this.page,
  });

  @override
  int get hashCode =>
      root.hashCode ^ replies.hashCode ^ hasNextPage.hashCode ^ page.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentsData &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          replies == other.replies &&
          hasNextPage == other.hasNextPage &&
          page == other.page;
}

class ConstantItem {
  final PlatformInt64 id;
  final String name;

  const ConstantItem({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConstantItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class DownloadProgress {
  final String mangaSlug;
  final String chapterNumber;
  final String chapterVolume;
  final PlatformInt64 currentPage;
  final PlatformInt64 totalPages;
  final PlatformInt64 currentChapter;
  final PlatformInt64 totalChapters;
  final PlatformInt64 bytesDownloaded;
  final DownloadState state;
  final String? errorMessage;

  const DownloadProgress({
    required this.mangaSlug,
    required this.chapterNumber,
    required this.chapterVolume,
    required this.currentPage,
    required this.totalPages,
    required this.currentChapter,
    required this.totalChapters,
    required this.bytesDownloaded,
    required this.state,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      mangaSlug.hashCode ^
      chapterNumber.hashCode ^
      chapterVolume.hashCode ^
      currentPage.hashCode ^
      totalPages.hashCode ^
      currentChapter.hashCode ^
      totalChapters.hashCode ^
      bytesDownloaded.hashCode ^
      state.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgress &&
          runtimeType == other.runtimeType &&
          mangaSlug == other.mangaSlug &&
          chapterNumber == other.chapterNumber &&
          chapterVolume == other.chapterVolume &&
          currentPage == other.currentPage &&
          totalPages == other.totalPages &&
          currentChapter == other.currentChapter &&
          totalChapters == other.totalChapters &&
          bytesDownloaded == other.bytesDownloaded &&
          state == other.state &&
          errorMessage == other.errorMessage;
}

enum DownloadState {
  queued,
  downloading,
  waitingForNetwork,
  paused,
  completed,
  failed,
  ;
}

class DownloadedChapterInfo {
  final PlatformInt64 id;
  final PlatformInt64 mangaId;
  final String volume;
  final String number;
  final PlatformInt64? branchId;
  final PlatformInt64 pageCount;
  final String downloadPath;
  final String downloadedAt;

  const DownloadedChapterInfo({
    required this.id,
    required this.mangaId,
    required this.volume,
    required this.number,
    this.branchId,
    required this.pageCount,
    required this.downloadPath,
    required this.downloadedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mangaId.hashCode ^
      volume.hashCode ^
      number.hashCode ^
      branchId.hashCode ^
      pageCount.hashCode ^
      downloadPath.hashCode ^
      downloadedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadedChapterInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mangaId == other.mangaId &&
          volume == other.volume &&
          number == other.number &&
          branchId == other.branchId &&
          pageCount == other.pageCount &&
          downloadPath == other.downloadPath &&
          downloadedAt == other.downloadedAt;
}

class DownloadedMangaGroup {
  final PlatformInt64 mangaId;
  final String slugUrl;
  final String name;
  final String rusName;
  final String coverUrl;
  final List<DownloadedChapterInfo> chapters;
  final PlatformInt64 totalSizeBytes;

  const DownloadedMangaGroup({
    required this.mangaId,
    required this.slugUrl,
    required this.name,
    required this.rusName,
    required this.coverUrl,
    required this.chapters,
    required this.totalSizeBytes,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      slugUrl.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      coverUrl.hashCode ^
      chapters.hashCode ^
      totalSizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadedMangaGroup &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          slugUrl == other.slugUrl &&
          name == other.name &&
          rusName == other.rusName &&
          coverUrl == other.coverUrl &&
          chapters == other.chapters &&
          totalSizeBytes == other.totalSizeBytes;
}

class Genre {
  final PlatformInt64 id;
  final String name;

  const Genre({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Genre &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class HomePageData {
  final List<MangaSearchResult> popular;
  final List<MangaSearchResult> newest;
  final List<MangaSearchResult> latestUpdates;
  final List<MangaSearchResult> topViews;

  const HomePageData({
    required this.popular,
    required this.newest,
    required this.latestUpdates,
    required this.topViews,
  });

  @override
  int get hashCode =>
      popular.hashCode ^
      newest.hashCode ^
      latestUpdates.hashCode ^
      topViews.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomePageData &&
          runtimeType == other.runtimeType &&
          popular == other.popular &&
          newest == other.newest &&
          latestUpdates == other.latestUpdates &&
          topViews == other.topViews;
}

class LibraryEntry {
  final PlatformInt64 mangaId;
  final String slugUrl;
  final String name;
  final String rusName;
  final String coverUrl;
  final ListType listType;
  final String addedAt;
  final String? lastReadChapter;
  final String? lastReadVolume;
  final PlatformInt64 unreadCount;
  final String ratingAverage;

  const LibraryEntry({
    required this.mangaId,
    required this.slugUrl,
    required this.name,
    required this.rusName,
    required this.coverUrl,
    required this.listType,
    required this.addedAt,
    this.lastReadChapter,
    this.lastReadVolume,
    required this.unreadCount,
    required this.ratingAverage,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      slugUrl.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      coverUrl.hashCode ^
      listType.hashCode ^
      addedAt.hashCode ^
      lastReadChapter.hashCode ^
      lastReadVolume.hashCode ^
      unreadCount.hashCode ^
      ratingAverage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryEntry &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          slugUrl == other.slugUrl &&
          name == other.name &&
          rusName == other.rusName &&
          coverUrl == other.coverUrl &&
          listType == other.listType &&
          addedAt == other.addedAt &&
          lastReadChapter == other.lastReadChapter &&
          lastReadVolume == other.lastReadVolume &&
          unreadCount == other.unreadCount &&
          ratingAverage == other.ratingAverage;
}

enum ListType {
  reading,
  planToRead,
  completed,
  dropped,
  favorites,
  onHold,
  ;

  Future<void> asStr() => RustLib.instance.api.crateApiModelsListTypeAsStr(
        that: this,
      );

  static Future<ListType?> fromStr({required String s}) =>
      RustLib.instance.api.crateApiModelsListTypeFromStr(s: s);
}

class MangaConstants {
  final List<ConstantItem> types;
  final List<ConstantItem> statuses;
  final List<ConstantItem> scanlateStatuses;
  final List<ConstantItem> ageRestrictions;
  final List<ConstantItem> formats;
  final List<ConstantItem> genres;
  final List<ConstantItem> tags;

  const MangaConstants({
    required this.types,
    required this.statuses,
    required this.scanlateStatuses,
    required this.ageRestrictions,
    required this.formats,
    required this.genres,
    required this.tags,
  });

  @override
  int get hashCode =>
      types.hashCode ^
      statuses.hashCode ^
      scanlateStatuses.hashCode ^
      ageRestrictions.hashCode ^
      formats.hashCode ^
      genres.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaConstants &&
          runtimeType == other.runtimeType &&
          types == other.types &&
          statuses == other.statuses &&
          scanlateStatuses == other.scanlateStatuses &&
          ageRestrictions == other.ageRestrictions &&
          formats == other.formats &&
          genres == other.genres &&
          tags == other.tags;
}

class MangaDetails {
  final PlatformInt64 id;
  final String name;
  final String rusName;
  final String engName;
  final String slug;
  final String slugUrl;
  final String coverUrl;
  final String coverThumbUrl;
  final String mangaType;
  final PlatformInt64 typeId;
  final String status;
  final PlatformInt64 statusId;
  final String ageRestriction;
  final String ratingAverage;
  final String ratingVotes;
  final String? releaseDate;
  final String summary;
  final List<Genre> genres;
  final List<Tag> tags;
  final List<Person> authors;
  final List<Person> artists;
  final String viewsTotal;
  final String viewsFormatted;
  final PlatformInt64 chaptersCount;
  final List<String> formatLabels;
  final String? publisherName;

  const MangaDetails({
    required this.id,
    required this.name,
    required this.rusName,
    required this.engName,
    required this.slug,
    required this.slugUrl,
    required this.coverUrl,
    required this.coverThumbUrl,
    required this.mangaType,
    required this.typeId,
    required this.status,
    required this.statusId,
    required this.ageRestriction,
    required this.ratingAverage,
    required this.ratingVotes,
    this.releaseDate,
    required this.summary,
    required this.genres,
    required this.tags,
    required this.authors,
    required this.artists,
    required this.viewsTotal,
    required this.viewsFormatted,
    required this.chaptersCount,
    required this.formatLabels,
    this.publisherName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      engName.hashCode ^
      slug.hashCode ^
      slugUrl.hashCode ^
      coverUrl.hashCode ^
      coverThumbUrl.hashCode ^
      mangaType.hashCode ^
      typeId.hashCode ^
      status.hashCode ^
      statusId.hashCode ^
      ageRestriction.hashCode ^
      ratingAverage.hashCode ^
      ratingVotes.hashCode ^
      releaseDate.hashCode ^
      summary.hashCode ^
      genres.hashCode ^
      tags.hashCode ^
      authors.hashCode ^
      artists.hashCode ^
      viewsTotal.hashCode ^
      viewsFormatted.hashCode ^
      chaptersCount.hashCode ^
      formatLabels.hashCode ^
      publisherName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          rusName == other.rusName &&
          engName == other.engName &&
          slug == other.slug &&
          slugUrl == other.slugUrl &&
          coverUrl == other.coverUrl &&
          coverThumbUrl == other.coverThumbUrl &&
          mangaType == other.mangaType &&
          typeId == other.typeId &&
          status == other.status &&
          statusId == other.statusId &&
          ageRestriction == other.ageRestriction &&
          ratingAverage == other.ratingAverage &&
          ratingVotes == other.ratingVotes &&
          releaseDate == other.releaseDate &&
          summary == other.summary &&
          genres == other.genres &&
          tags == other.tags &&
          authors == other.authors &&
          artists == other.artists &&
          viewsTotal == other.viewsTotal &&
          viewsFormatted == other.viewsFormatted &&
          chaptersCount == other.chaptersCount &&
          formatLabels == other.formatLabels &&
          publisherName == other.publisherName;
}

class MangaRelationItem {
  final String relationTitle;
  final MangaSearchResult manga;

  const MangaRelationItem({
    required this.relationTitle,
    required this.manga,
  });

  @override
  int get hashCode => relationTitle.hashCode ^ manga.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaRelationItem &&
          runtimeType == other.runtimeType &&
          relationTitle == other.relationTitle &&
          manga == other.manga;
}

class MangaSearchResult {
  final PlatformInt64 id;
  final String name;
  final String rusName;
  final String engName;
  final String slug;
  final String slugUrl;
  final String coverUrl;
  final String coverThumbUrl;
  final String mangaType;
  final PlatformInt64 typeId;
  final String status;
  final PlatformInt64 statusId;
  final String ageRestriction;
  final String ratingAverage;
  final String ratingVotes;
  final String? releaseDate;

  const MangaSearchResult({
    required this.id,
    required this.name,
    required this.rusName,
    required this.engName,
    required this.slug,
    required this.slugUrl,
    required this.coverUrl,
    required this.coverThumbUrl,
    required this.mangaType,
    required this.typeId,
    required this.status,
    required this.statusId,
    required this.ageRestriction,
    required this.ratingAverage,
    required this.ratingVotes,
    this.releaseDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      engName.hashCode ^
      slug.hashCode ^
      slugUrl.hashCode ^
      coverUrl.hashCode ^
      coverThumbUrl.hashCode ^
      mangaType.hashCode ^
      typeId.hashCode ^
      status.hashCode ^
      statusId.hashCode ^
      ageRestriction.hashCode ^
      ratingAverage.hashCode ^
      ratingVotes.hashCode ^
      releaseDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaSearchResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          rusName == other.rusName &&
          engName == other.engName &&
          slug == other.slug &&
          slugUrl == other.slugUrl &&
          coverUrl == other.coverUrl &&
          coverThumbUrl == other.coverThumbUrl &&
          mangaType == other.mangaType &&
          typeId == other.typeId &&
          status == other.status &&
          statusId == other.statusId &&
          ageRestriction == other.ageRestriction &&
          ratingAverage == other.ratingAverage &&
          ratingVotes == other.ratingVotes &&
          releaseDate == other.releaseDate;
}

class MangaSimilarItem {
  final String reason;
  final PlatformInt64 votesUp;
  final PlatformInt64 votesDown;
  final MangaSearchResult manga;

  const MangaSimilarItem({
    required this.reason,
    required this.votesUp,
    required this.votesDown,
    required this.manga,
  });

  @override
  int get hashCode =>
      reason.hashCode ^ votesUp.hashCode ^ votesDown.hashCode ^ manga.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaSimilarItem &&
          runtimeType == other.runtimeType &&
          reason == other.reason &&
          votesUp == other.votesUp &&
          votesDown == other.votesDown &&
          manga == other.manga;
}

class Person {
  final PlatformInt64 id;
  final String name;
  final String slug;

  const Person({
    required this.id,
    required this.name,
    required this.slug,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ slug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Person &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          slug == other.slug;
}

class ReadingPosition {
  final PlatformInt64 mangaId;
  final String chapterVolume;
  final String chapterNumber;
  final PlatformInt64 pageIndex;
  final double scrollPosition;
  final String lastReadAt;

  const ReadingPosition({
    required this.mangaId,
    required this.chapterVolume,
    required this.chapterNumber,
    required this.pageIndex,
    required this.scrollPosition,
    required this.lastReadAt,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      chapterVolume.hashCode ^
      chapterNumber.hashCode ^
      pageIndex.hashCode ^
      scrollPosition.hashCode ^
      lastReadAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingPosition &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          chapterVolume == other.chapterVolume &&
          chapterNumber == other.chapterNumber &&
          pageIndex == other.pageIndex &&
          scrollPosition == other.scrollPosition &&
          lastReadAt == other.lastReadAt;
}

class Tag {
  final PlatformInt64 id;
  final String name;

  const Tag({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
