// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ContentFilterItem`, `LibraryUpdateItem`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AppSettingItem {
  final String key;
  final String value;

  const AppSettingItem({
    required this.key,
    required this.value,
  });

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingItem &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class Chapter {
  final PlatformInt64 id;
  final String volume;
  final String number;
  final String? name;
  final PlatformInt64? branchId;
  final PlatformInt64 branchesCount;
  final bool isPaid;

  const Chapter({
    required this.id,
    required this.volume,
    required this.number,
    this.name,
    this.branchId,
    required this.branchesCount,
    required this.isPaid,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      volume.hashCode ^
      number.hashCode ^
      name.hashCode ^
      branchId.hashCode ^
      branchesCount.hashCode ^
      isPaid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chapter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          volume == other.volume &&
          number == other.number &&
          name == other.name &&
          branchId == other.branchId &&
          branchesCount == other.branchesCount &&
          isPaid == other.isPaid;
}

class ChapterDownloadRequest {
  final String volume;
  final String number;
  final PlatformInt64? branchId;

  const ChapterDownloadRequest({
    required this.volume,
    required this.number,
    this.branchId,
  });

  @override
  int get hashCode => volume.hashCode ^ number.hashCode ^ branchId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterDownloadRequest &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          number == other.number &&
          branchId == other.branchId;
}

class ChapterHistory {
  final PlatformInt64 mangaId;
  final String volume;
  final String number;
  final PlatformInt64 pageIndex;
  final PlatformInt64 totalPages;
  final bool isCompleted;
  final String lastReadAt;

  const ChapterHistory({
    required this.mangaId,
    required this.volume,
    required this.number,
    required this.pageIndex,
    required this.totalPages,
    required this.isCompleted,
    required this.lastReadAt,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      volume.hashCode ^
      number.hashCode ^
      pageIndex.hashCode ^
      totalPages.hashCode ^
      isCompleted.hashCode ^
      lastReadAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterHistory &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          volume == other.volume &&
          number == other.number &&
          pageIndex == other.pageIndex &&
          totalPages == other.totalPages &&
          isCompleted == other.isCompleted &&
          lastReadAt == other.lastReadAt;
}

class ChapterPage {
  final String url;
  final PlatformInt64? width;
  final PlatformInt64? height;

  const ChapterPage({
    required this.url,
    this.width,
    this.height,
  });

  @override
  int get hashCode => url.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterPage &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          width == other.width &&
          height == other.height;
}

class CommentItem {
  final PlatformInt64 id;
  final PlatformInt64 userId;
  final PlatformInt64? rootId;
  final PlatformInt64? parentComment;
  final PlatformInt64 commentLevel;
  final PlatformInt64? postPage;
  final String text;
  final String createdAt;
  final String username;
  final String userAvatar;
  final PlatformInt64 votesUp;
  final PlatformInt64 votesDown;
  final PlatformInt64? userVote;

  const CommentItem({
    required this.id,
    required this.userId,
    this.rootId,
    this.parentComment,
    required this.commentLevel,
    this.postPage,
    required this.text,
    required this.createdAt,
    required this.username,
    required this.userAvatar,
    required this.votesUp,
    required this.votesDown,
    this.userVote,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      rootId.hashCode ^
      parentComment.hashCode ^
      commentLevel.hashCode ^
      postPage.hashCode ^
      text.hashCode ^
      createdAt.hashCode ^
      username.hashCode ^
      userAvatar.hashCode ^
      votesUp.hashCode ^
      votesDown.hashCode ^
      userVote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          rootId == other.rootId &&
          parentComment == other.parentComment &&
          commentLevel == other.commentLevel &&
          postPage == other.postPage &&
          text == other.text &&
          createdAt == other.createdAt &&
          username == other.username &&
          userAvatar == other.userAvatar &&
          votesUp == other.votesUp &&
          votesDown == other.votesDown &&
          userVote == other.userVote;
}

class CommentVoteResult {
  final bool success;
  final PlatformInt64 votesUp;
  final PlatformInt64 votesDown;
  final PlatformInt64? userVote;

  const CommentVoteResult({
    required this.success,
    required this.votesUp,
    required this.votesDown,
    this.userVote,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      votesUp.hashCode ^
      votesDown.hashCode ^
      userVote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentVoteResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          votesUp == other.votesUp &&
          votesDown == other.votesDown &&
          userVote == other.userVote;
}

class CommentsData {
  final List<CommentItem> root;
  final List<CommentItem> replies;
  final bool hasNextPage;
  final PlatformInt64 page;

  const CommentsData({
    required this.root,
    required this.replies,
    required this.hasNextPage,
    required this.page,
  });

  @override
  int get hashCode =>
      root.hashCode ^ replies.hashCode ^ hasNextPage.hashCode ^ page.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentsData &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          replies == other.replies &&
          hasNextPage == other.hasNextPage &&
          page == other.page;
}

class ConstantItem {
  final PlatformInt64 id;
  final String name;

  const ConstantItem({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConstantItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class ContinueReadingItem {
  final PlatformInt64 mangaId;
  final String slugUrl;
  final String name;
  final String rusName;
  final String coverUrl;
  final String lastReadVolume;
  final String lastReadChapter;
  final String lastReadAt;
  final PlatformInt64 totalChapters;
  final PlatformInt64 readChapters;
  final PlatformInt64 unreadCount;
  final bool hasNewChapters;
  final PlatformInt64 newChaptersCount;

  const ContinueReadingItem({
    required this.mangaId,
    required this.slugUrl,
    required this.name,
    required this.rusName,
    required this.coverUrl,
    required this.lastReadVolume,
    required this.lastReadChapter,
    required this.lastReadAt,
    required this.totalChapters,
    required this.readChapters,
    required this.unreadCount,
    required this.hasNewChapters,
    required this.newChaptersCount,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      slugUrl.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      coverUrl.hashCode ^
      lastReadVolume.hashCode ^
      lastReadChapter.hashCode ^
      lastReadAt.hashCode ^
      totalChapters.hashCode ^
      readChapters.hashCode ^
      unreadCount.hashCode ^
      hasNewChapters.hashCode ^
      newChaptersCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContinueReadingItem &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          slugUrl == other.slugUrl &&
          name == other.name &&
          rusName == other.rusName &&
          coverUrl == other.coverUrl &&
          lastReadVolume == other.lastReadVolume &&
          lastReadChapter == other.lastReadChapter &&
          lastReadAt == other.lastReadAt &&
          totalChapters == other.totalChapters &&
          readChapters == other.readChapters &&
          unreadCount == other.unreadCount &&
          hasNewChapters == other.hasNewChapters &&
          newChaptersCount == other.newChaptersCount;
}

class CustomUserList {
  final PlatformInt64 id;
  final String name;
  final String color;
  final String createdAt;
  final PlatformInt64 itemsCount;

  const CustomUserList({
    required this.id,
    required this.name,
    required this.color,
    required this.createdAt,
    required this.itemsCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      color.hashCode ^
      createdAt.hashCode ^
      itemsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomUserList &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          createdAt == other.createdAt &&
          itemsCount == other.itemsCount;
}

class DownloadProgress {
  final String mangaSlug;
  final String chapterNumber;
  final String chapterVolume;
  final PlatformInt64 currentPage;
  final PlatformInt64 totalPages;
  final PlatformInt64 currentChapter;
  final PlatformInt64 totalChapters;
  final PlatformInt64 bytesDownloaded;
  final DownloadState state;
  final String? errorMessage;

  const DownloadProgress({
    required this.mangaSlug,
    required this.chapterNumber,
    required this.chapterVolume,
    required this.currentPage,
    required this.totalPages,
    required this.currentChapter,
    required this.totalChapters,
    required this.bytesDownloaded,
    required this.state,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      mangaSlug.hashCode ^
      chapterNumber.hashCode ^
      chapterVolume.hashCode ^
      currentPage.hashCode ^
      totalPages.hashCode ^
      currentChapter.hashCode ^
      totalChapters.hashCode ^
      bytesDownloaded.hashCode ^
      state.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgress &&
          runtimeType == other.runtimeType &&
          mangaSlug == other.mangaSlug &&
          chapterNumber == other.chapterNumber &&
          chapterVolume == other.chapterVolume &&
          currentPage == other.currentPage &&
          totalPages == other.totalPages &&
          currentChapter == other.currentChapter &&
          totalChapters == other.totalChapters &&
          bytesDownloaded == other.bytesDownloaded &&
          state == other.state &&
          errorMessage == other.errorMessage;
}

enum DownloadState {
  queued,
  downloading,
  waitingForNetwork,
  paused,
  completed,
  failed,
  ;
}

class DownloadedChapterInfo {
  final PlatformInt64 id;
  final PlatformInt64 mangaId;
  final String volume;
  final String number;
  final PlatformInt64? branchId;
  final PlatformInt64 pageCount;
  final String downloadPath;
  final String downloadedAt;

  const DownloadedChapterInfo({
    required this.id,
    required this.mangaId,
    required this.volume,
    required this.number,
    this.branchId,
    required this.pageCount,
    required this.downloadPath,
    required this.downloadedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mangaId.hashCode ^
      volume.hashCode ^
      number.hashCode ^
      branchId.hashCode ^
      pageCount.hashCode ^
      downloadPath.hashCode ^
      downloadedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadedChapterInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mangaId == other.mangaId &&
          volume == other.volume &&
          number == other.number &&
          branchId == other.branchId &&
          pageCount == other.pageCount &&
          downloadPath == other.downloadPath &&
          downloadedAt == other.downloadedAt;
}

class DownloadedMangaGroup {
  final PlatformInt64 mangaId;
  final String slugUrl;
  final String name;
  final String rusName;
  final String coverUrl;
  final List<DownloadedChapterInfo> chapters;
  final PlatformInt64 totalSizeBytes;

  const DownloadedMangaGroup({
    required this.mangaId,
    required this.slugUrl,
    required this.name,
    required this.rusName,
    required this.coverUrl,
    required this.chapters,
    required this.totalSizeBytes,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      slugUrl.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      coverUrl.hashCode ^
      chapters.hashCode ^
      totalSizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadedMangaGroup &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          slugUrl == other.slugUrl &&
          name == other.name &&
          rusName == other.rusName &&
          coverUrl == other.coverUrl &&
          chapters == other.chapters &&
          totalSizeBytes == other.totalSizeBytes;
}

class Genre {
  final PlatformInt64 id;
  final String name;

  const Genre({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Genre &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class GenreCount {
  final String name;
  final PlatformInt64 count;
  final double percentage;

  const GenreCount({
    required this.name,
    required this.count,
    required this.percentage,
  });

  @override
  int get hashCode => name.hashCode ^ count.hashCode ^ percentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenreCount &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          count == other.count &&
          percentage == other.percentage;
}

class HomePageData {
  final List<MangaSearchResult> popular;
  final List<MangaSearchResult> newest;
  final List<MangaSearchResult> latestUpdates;
  final List<MangaSearchResult> topViews;

  const HomePageData({
    required this.popular,
    required this.newest,
    required this.latestUpdates,
    required this.topViews,
  });

  @override
  int get hashCode =>
      popular.hashCode ^
      newest.hashCode ^
      latestUpdates.hashCode ^
      topViews.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomePageData &&
          runtimeType == other.runtimeType &&
          popular == other.popular &&
          newest == other.newest &&
          latestUpdates == other.latestUpdates &&
          topViews == other.topViews;
}

class LibraryEntry {
  final PlatformInt64 mangaId;
  final String slugUrl;
  final String name;
  final String rusName;
  final String coverUrl;
  final ListType listType;
  final String addedAt;
  final String? lastReadChapter;
  final String? lastReadVolume;
  final PlatformInt64 unreadCount;
  final String ratingAverage;
  final PlatformInt64 totalChapters;
  final PlatformInt64 readChapters;

  const LibraryEntry({
    required this.mangaId,
    required this.slugUrl,
    required this.name,
    required this.rusName,
    required this.coverUrl,
    required this.listType,
    required this.addedAt,
    this.lastReadChapter,
    this.lastReadVolume,
    required this.unreadCount,
    required this.ratingAverage,
    required this.totalChapters,
    required this.readChapters,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      slugUrl.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      coverUrl.hashCode ^
      listType.hashCode ^
      addedAt.hashCode ^
      lastReadChapter.hashCode ^
      lastReadVolume.hashCode ^
      unreadCount.hashCode ^
      ratingAverage.hashCode ^
      totalChapters.hashCode ^
      readChapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryEntry &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          slugUrl == other.slugUrl &&
          name == other.name &&
          rusName == other.rusName &&
          coverUrl == other.coverUrl &&
          listType == other.listType &&
          addedAt == other.addedAt &&
          lastReadChapter == other.lastReadChapter &&
          lastReadVolume == other.lastReadVolume &&
          unreadCount == other.unreadCount &&
          ratingAverage == other.ratingAverage &&
          totalChapters == other.totalChapters &&
          readChapters == other.readChapters;
}

enum ListType {
  reading,
  planToRead,
  completed,
  dropped,
  favorites,
  onHold,
  ;

  Future<void> asStr() => RustLib.instance.api.crateApiModelsListTypeAsStr(
        that: this,
      );

  static Future<ListType?> fromStr({required String s}) =>
      RustLib.instance.api.crateApiModelsListTypeFromStr(s: s);
}

class MalImportResult {
  final PlatformInt64 importedCount;
  final PlatformInt64 updatedCount;
  final PlatformInt64 failedCount;

  const MalImportResult({
    required this.importedCount,
    required this.updatedCount,
    required this.failedCount,
  });

  @override
  int get hashCode =>
      importedCount.hashCode ^ updatedCount.hashCode ^ failedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MalImportResult &&
          runtimeType == other.runtimeType &&
          importedCount == other.importedCount &&
          updatedCount == other.updatedCount &&
          failedCount == other.failedCount;
}

class MangaCollectionDetails {
  final PlatformInt64 id;
  final String name;
  final String description;
  final PlatformInt64 views;
  final PlatformInt64 favoritesCount;
  final PlatformInt64 itemsCount;
  final PlatformInt64 commentsCount;
  final PlatformInt64 userId;
  final String username;
  final String userAvatar;
  final String createdAt;
  final List<MangaSearchResult> items;

  const MangaCollectionDetails({
    required this.id,
    required this.name,
    required this.description,
    required this.views,
    required this.favoritesCount,
    required this.itemsCount,
    required this.commentsCount,
    required this.userId,
    required this.username,
    required this.userAvatar,
    required this.createdAt,
    required this.items,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      views.hashCode ^
      favoritesCount.hashCode ^
      itemsCount.hashCode ^
      commentsCount.hashCode ^
      userId.hashCode ^
      username.hashCode ^
      userAvatar.hashCode ^
      createdAt.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaCollectionDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          views == other.views &&
          favoritesCount == other.favoritesCount &&
          itemsCount == other.itemsCount &&
          commentsCount == other.commentsCount &&
          userId == other.userId &&
          username == other.username &&
          userAvatar == other.userAvatar &&
          createdAt == other.createdAt &&
          items == other.items;
}

class MangaCollectionItem {
  final PlatformInt64 id;
  final String name;
  final String description;
  final String typeName;
  final PlatformInt64 views;
  final PlatformInt64 favoritesCount;
  final PlatformInt64 itemsCount;
  final PlatformInt64 commentsCount;
  final PlatformInt64 votesUp;
  final PlatformInt64 votesDown;
  final String? coverUrl;
  final PlatformInt64 userId;
  final String username;
  final String userAvatar;
  final String createdAt;

  const MangaCollectionItem({
    required this.id,
    required this.name,
    required this.description,
    required this.typeName,
    required this.views,
    required this.favoritesCount,
    required this.itemsCount,
    required this.commentsCount,
    required this.votesUp,
    required this.votesDown,
    this.coverUrl,
    required this.userId,
    required this.username,
    required this.userAvatar,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      typeName.hashCode ^
      views.hashCode ^
      favoritesCount.hashCode ^
      itemsCount.hashCode ^
      commentsCount.hashCode ^
      votesUp.hashCode ^
      votesDown.hashCode ^
      coverUrl.hashCode ^
      userId.hashCode ^
      username.hashCode ^
      userAvatar.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaCollectionItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          typeName == other.typeName &&
          views == other.views &&
          favoritesCount == other.favoritesCount &&
          itemsCount == other.itemsCount &&
          commentsCount == other.commentsCount &&
          votesUp == other.votesUp &&
          votesDown == other.votesDown &&
          coverUrl == other.coverUrl &&
          userId == other.userId &&
          username == other.username &&
          userAvatar == other.userAvatar &&
          createdAt == other.createdAt;
}

class MangaConstants {
  final List<ConstantItem> types;
  final List<ConstantItem> statuses;
  final List<ConstantItem> scanlateStatuses;
  final List<ConstantItem> ageRestrictions;
  final List<ConstantItem> formats;
  final List<ConstantItem> genres;
  final List<ConstantItem> tags;

  const MangaConstants({
    required this.types,
    required this.statuses,
    required this.scanlateStatuses,
    required this.ageRestrictions,
    required this.formats,
    required this.genres,
    required this.tags,
  });

  @override
  int get hashCode =>
      types.hashCode ^
      statuses.hashCode ^
      scanlateStatuses.hashCode ^
      ageRestrictions.hashCode ^
      formats.hashCode ^
      genres.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaConstants &&
          runtimeType == other.runtimeType &&
          types == other.types &&
          statuses == other.statuses &&
          scanlateStatuses == other.scanlateStatuses &&
          ageRestrictions == other.ageRestrictions &&
          formats == other.formats &&
          genres == other.genres &&
          tags == other.tags;
}

class MangaDetails {
  final PlatformInt64 id;
  final String name;
  final String rusName;
  final String engName;
  final String slug;
  final String slugUrl;
  final String coverUrl;
  final String coverThumbUrl;
  final String mangaType;
  final PlatformInt64 typeId;
  final String status;
  final PlatformInt64 statusId;
  final String ageRestriction;
  final String ratingAverage;
  final String ratingVotes;
  final String? releaseDate;
  final String summary;
  final List<Genre> genres;
  final List<Tag> tags;
  final List<Person> authors;
  final List<Person> artists;
  final String viewsTotal;
  final String viewsFormatted;
  final PlatformInt64 chaptersCount;
  final List<String> formatLabels;
  final String? publisherName;

  const MangaDetails({
    required this.id,
    required this.name,
    required this.rusName,
    required this.engName,
    required this.slug,
    required this.slugUrl,
    required this.coverUrl,
    required this.coverThumbUrl,
    required this.mangaType,
    required this.typeId,
    required this.status,
    required this.statusId,
    required this.ageRestriction,
    required this.ratingAverage,
    required this.ratingVotes,
    this.releaseDate,
    required this.summary,
    required this.genres,
    required this.tags,
    required this.authors,
    required this.artists,
    required this.viewsTotal,
    required this.viewsFormatted,
    required this.chaptersCount,
    required this.formatLabels,
    this.publisherName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      engName.hashCode ^
      slug.hashCode ^
      slugUrl.hashCode ^
      coverUrl.hashCode ^
      coverThumbUrl.hashCode ^
      mangaType.hashCode ^
      typeId.hashCode ^
      status.hashCode ^
      statusId.hashCode ^
      ageRestriction.hashCode ^
      ratingAverage.hashCode ^
      ratingVotes.hashCode ^
      releaseDate.hashCode ^
      summary.hashCode ^
      genres.hashCode ^
      tags.hashCode ^
      authors.hashCode ^
      artists.hashCode ^
      viewsTotal.hashCode ^
      viewsFormatted.hashCode ^
      chaptersCount.hashCode ^
      formatLabels.hashCode ^
      publisherName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          rusName == other.rusName &&
          engName == other.engName &&
          slug == other.slug &&
          slugUrl == other.slugUrl &&
          coverUrl == other.coverUrl &&
          coverThumbUrl == other.coverThumbUrl &&
          mangaType == other.mangaType &&
          typeId == other.typeId &&
          status == other.status &&
          statusId == other.statusId &&
          ageRestriction == other.ageRestriction &&
          ratingAverage == other.ratingAverage &&
          ratingVotes == other.ratingVotes &&
          releaseDate == other.releaseDate &&
          summary == other.summary &&
          genres == other.genres &&
          tags == other.tags &&
          authors == other.authors &&
          artists == other.artists &&
          viewsTotal == other.viewsTotal &&
          viewsFormatted == other.viewsFormatted &&
          chaptersCount == other.chaptersCount &&
          formatLabels == other.formatLabels &&
          publisherName == other.publisherName;
}

class MangaRecapData {
  final PlatformInt64 totalChaptersRead;
  final PlatformInt64 totalPagesRead;
  final double estimatedReadingHours;
  final PlatformInt64 currentStreak;
  final PlatformInt64 maxStreak;
  final PlatformInt64 activeDaysCount;
  final List<GenreCount> topGenres;
  final List<RecapMangaItem> topManga;
  final TimeOfDayDistribution timeOfDay;

  const MangaRecapData({
    required this.totalChaptersRead,
    required this.totalPagesRead,
    required this.estimatedReadingHours,
    required this.currentStreak,
    required this.maxStreak,
    required this.activeDaysCount,
    required this.topGenres,
    required this.topManga,
    required this.timeOfDay,
  });

  @override
  int get hashCode =>
      totalChaptersRead.hashCode ^
      totalPagesRead.hashCode ^
      estimatedReadingHours.hashCode ^
      currentStreak.hashCode ^
      maxStreak.hashCode ^
      activeDaysCount.hashCode ^
      topGenres.hashCode ^
      topManga.hashCode ^
      timeOfDay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaRecapData &&
          runtimeType == other.runtimeType &&
          totalChaptersRead == other.totalChaptersRead &&
          totalPagesRead == other.totalPagesRead &&
          estimatedReadingHours == other.estimatedReadingHours &&
          currentStreak == other.currentStreak &&
          maxStreak == other.maxStreak &&
          activeDaysCount == other.activeDaysCount &&
          topGenres == other.topGenres &&
          topManga == other.topManga &&
          timeOfDay == other.timeOfDay;
}

class MangaRelationItem {
  final String relationTitle;
  final MangaSearchResult manga;

  const MangaRelationItem({
    required this.relationTitle,
    required this.manga,
  });

  @override
  int get hashCode => relationTitle.hashCode ^ manga.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaRelationItem &&
          runtimeType == other.runtimeType &&
          relationTitle == other.relationTitle &&
          manga == other.manga;
}

class MangaSearchResult {
  final PlatformInt64 id;
  final String name;
  final String rusName;
  final String engName;
  final String slug;
  final String slugUrl;
  final String coverUrl;
  final String coverThumbUrl;
  final String mangaType;
  final PlatformInt64 typeId;
  final String status;
  final PlatformInt64 statusId;
  final String ageRestriction;
  final String ratingAverage;
  final String ratingVotes;
  final String? releaseDate;

  const MangaSearchResult({
    required this.id,
    required this.name,
    required this.rusName,
    required this.engName,
    required this.slug,
    required this.slugUrl,
    required this.coverUrl,
    required this.coverThumbUrl,
    required this.mangaType,
    required this.typeId,
    required this.status,
    required this.statusId,
    required this.ageRestriction,
    required this.ratingAverage,
    required this.ratingVotes,
    this.releaseDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      engName.hashCode ^
      slug.hashCode ^
      slugUrl.hashCode ^
      coverUrl.hashCode ^
      coverThumbUrl.hashCode ^
      mangaType.hashCode ^
      typeId.hashCode ^
      status.hashCode ^
      statusId.hashCode ^
      ageRestriction.hashCode ^
      ratingAverage.hashCode ^
      ratingVotes.hashCode ^
      releaseDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaSearchResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          rusName == other.rusName &&
          engName == other.engName &&
          slug == other.slug &&
          slugUrl == other.slugUrl &&
          coverUrl == other.coverUrl &&
          coverThumbUrl == other.coverThumbUrl &&
          mangaType == other.mangaType &&
          typeId == other.typeId &&
          status == other.status &&
          statusId == other.statusId &&
          ageRestriction == other.ageRestriction &&
          ratingAverage == other.ratingAverage &&
          ratingVotes == other.ratingVotes &&
          releaseDate == other.releaseDate;
}

class MangaSimilarItem {
  final String reason;
  final PlatformInt64 votesUp;
  final PlatformInt64 votesDown;
  final MangaSearchResult manga;

  const MangaSimilarItem({
    required this.reason,
    required this.votesUp,
    required this.votesDown,
    required this.manga,
  });

  @override
  int get hashCode =>
      reason.hashCode ^ votesUp.hashCode ^ votesDown.hashCode ^ manga.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaSimilarItem &&
          runtimeType == other.runtimeType &&
          reason == other.reason &&
          votesUp == other.votesUp &&
          votesDown == other.votesDown &&
          manga == other.manga;
}

class NotificationCountInfo {
  final PlatformInt64 count;
  final PlatformInt64 unreadCards;

  const NotificationCountInfo({
    required this.count,
    required this.unreadCards,
  });

  @override
  int get hashCode => count.hashCode ^ unreadCards.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationCountInfo &&
          runtimeType == other.runtimeType &&
          count == other.count &&
          unreadCards == other.unreadCards;
}

class Person {
  final PlatformInt64 id;
  final String name;
  final String slug;

  const Person({
    required this.id,
    required this.name,
    required this.slug,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ slug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Person &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          slug == other.slug;
}

class ReadingHistoryItem {
  final PlatformInt64 mangaId;
  final String slugUrl;
  final String name;
  final String rusName;
  final String coverUrl;
  final String volume;
  final String number;
  final bool isCompleted;
  final String lastReadAt;
  final PlatformInt64 totalPages;
  final PlatformInt64 pageIndex;

  const ReadingHistoryItem({
    required this.mangaId,
    required this.slugUrl,
    required this.name,
    required this.rusName,
    required this.coverUrl,
    required this.volume,
    required this.number,
    required this.isCompleted,
    required this.lastReadAt,
    required this.totalPages,
    required this.pageIndex,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      slugUrl.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      coverUrl.hashCode ^
      volume.hashCode ^
      number.hashCode ^
      isCompleted.hashCode ^
      lastReadAt.hashCode ^
      totalPages.hashCode ^
      pageIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingHistoryItem &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          slugUrl == other.slugUrl &&
          name == other.name &&
          rusName == other.rusName &&
          coverUrl == other.coverUrl &&
          volume == other.volume &&
          number == other.number &&
          isCompleted == other.isCompleted &&
          lastReadAt == other.lastReadAt &&
          totalPages == other.totalPages &&
          pageIndex == other.pageIndex;
}

class ReadingPosition {
  final PlatformInt64 mangaId;
  final String chapterVolume;
  final String chapterNumber;
  final PlatformInt64 pageIndex;
  final double scrollPosition;
  final String lastReadAt;

  const ReadingPosition({
    required this.mangaId,
    required this.chapterVolume,
    required this.chapterNumber,
    required this.pageIndex,
    required this.scrollPosition,
    required this.lastReadAt,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      chapterVolume.hashCode ^
      chapterNumber.hashCode ^
      pageIndex.hashCode ^
      scrollPosition.hashCode ^
      lastReadAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingPosition &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          chapterVolume == other.chapterVolume &&
          chapterNumber == other.chapterNumber &&
          pageIndex == other.pageIndex &&
          scrollPosition == other.scrollPosition &&
          lastReadAt == other.lastReadAt;
}

class ReadingSessionInfo {
  final PlatformInt64 totalReadingSeconds;
  final PlatformInt64 totalSessions;
  final PlatformInt64 avgSessionSeconds;
  final PlatformInt64 todayReadingSeconds;
  final PlatformInt64 weekReadingSeconds;

  const ReadingSessionInfo({
    required this.totalReadingSeconds,
    required this.totalSessions,
    required this.avgSessionSeconds,
    required this.todayReadingSeconds,
    required this.weekReadingSeconds,
  });

  @override
  int get hashCode =>
      totalReadingSeconds.hashCode ^
      totalSessions.hashCode ^
      avgSessionSeconds.hashCode ^
      todayReadingSeconds.hashCode ^
      weekReadingSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingSessionInfo &&
          runtimeType == other.runtimeType &&
          totalReadingSeconds == other.totalReadingSeconds &&
          totalSessions == other.totalSessions &&
          avgSessionSeconds == other.avgSessionSeconds &&
          todayReadingSeconds == other.todayReadingSeconds &&
          weekReadingSeconds == other.weekReadingSeconds;
}

class ReadingStatistics {
  final PlatformInt64 totalChaptersRead;
  final PlatformInt64 totalPagesRead;
  final PlatformInt64 completedMangaCount;
  final PlatformInt64 inProgressMangaCount;
  final PlatformInt64 totalLibraryCount;
  final PlatformInt64 totalDownloadedChapters;
  final PlatformInt64 currentStreakDays;
  final PlatformInt64 maxStreakDays;
  final PlatformInt64 totalActiveDays;
  final List<GenreCount> topGenres;
  final TimeOfDayDistribution timeOfDay;

  const ReadingStatistics({
    required this.totalChaptersRead,
    required this.totalPagesRead,
    required this.completedMangaCount,
    required this.inProgressMangaCount,
    required this.totalLibraryCount,
    required this.totalDownloadedChapters,
    required this.currentStreakDays,
    required this.maxStreakDays,
    required this.totalActiveDays,
    required this.topGenres,
    required this.timeOfDay,
  });

  @override
  int get hashCode =>
      totalChaptersRead.hashCode ^
      totalPagesRead.hashCode ^
      completedMangaCount.hashCode ^
      inProgressMangaCount.hashCode ^
      totalLibraryCount.hashCode ^
      totalDownloadedChapters.hashCode ^
      currentStreakDays.hashCode ^
      maxStreakDays.hashCode ^
      totalActiveDays.hashCode ^
      topGenres.hashCode ^
      timeOfDay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingStatistics &&
          runtimeType == other.runtimeType &&
          totalChaptersRead == other.totalChaptersRead &&
          totalPagesRead == other.totalPagesRead &&
          completedMangaCount == other.completedMangaCount &&
          inProgressMangaCount == other.inProgressMangaCount &&
          totalLibraryCount == other.totalLibraryCount &&
          totalDownloadedChapters == other.totalDownloadedChapters &&
          currentStreakDays == other.currentStreakDays &&
          maxStreakDays == other.maxStreakDays &&
          totalActiveDays == other.totalActiveDays &&
          topGenres == other.topGenres &&
          timeOfDay == other.timeOfDay;
}

class ReadingStreakInfo {
  final PlatformInt64 currentStreak;
  final PlatformInt64 maxStreak;
  final String lastReadDate;
  final PlatformInt64 todayChaptersCount;
  final bool isActiveToday;
  final PlatformInt64 totalDaysRead;
  final PlatformInt64 totalChaptersRead;
  final List<String> historyDates;

  const ReadingStreakInfo({
    required this.currentStreak,
    required this.maxStreak,
    required this.lastReadDate,
    required this.todayChaptersCount,
    required this.isActiveToday,
    required this.totalDaysRead,
    required this.totalChaptersRead,
    required this.historyDates,
  });

  @override
  int get hashCode =>
      currentStreak.hashCode ^
      maxStreak.hashCode ^
      lastReadDate.hashCode ^
      todayChaptersCount.hashCode ^
      isActiveToday.hashCode ^
      totalDaysRead.hashCode ^
      totalChaptersRead.hashCode ^
      historyDates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingStreakInfo &&
          runtimeType == other.runtimeType &&
          currentStreak == other.currentStreak &&
          maxStreak == other.maxStreak &&
          lastReadDate == other.lastReadDate &&
          todayChaptersCount == other.todayChaptersCount &&
          isActiveToday == other.isActiveToday &&
          totalDaysRead == other.totalDaysRead &&
          totalChaptersRead == other.totalChaptersRead &&
          historyDates == other.historyDates;
}

class RecapMangaItem {
  final PlatformInt64 mangaId;
  final String name;
  final String rusName;
  final String coverUrl;
  final PlatformInt64 chaptersRead;

  const RecapMangaItem({
    required this.mangaId,
    required this.name,
    required this.rusName,
    required this.coverUrl,
    required this.chaptersRead,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      coverUrl.hashCode ^
      chaptersRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecapMangaItem &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          name == other.name &&
          rusName == other.rusName &&
          coverUrl == other.coverUrl &&
          chaptersRead == other.chaptersRead;
}

class RecommendedManga {
  final PlatformInt64 mangaId;
  final String slugUrl;
  final String name;
  final String rusName;
  final String coverUrl;
  final String coverThumbUrl;
  final String mangaType;
  final String ratingAverage;
  final double score;
  final String reason;

  const RecommendedManga({
    required this.mangaId,
    required this.slugUrl,
    required this.name,
    required this.rusName,
    required this.coverUrl,
    required this.coverThumbUrl,
    required this.mangaType,
    required this.ratingAverage,
    required this.score,
    required this.reason,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      slugUrl.hashCode ^
      name.hashCode ^
      rusName.hashCode ^
      coverUrl.hashCode ^
      coverThumbUrl.hashCode ^
      mangaType.hashCode ^
      ratingAverage.hashCode ^
      score.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendedManga &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          slugUrl == other.slugUrl &&
          name == other.name &&
          rusName == other.rusName &&
          coverUrl == other.coverUrl &&
          coverThumbUrl == other.coverThumbUrl &&
          mangaType == other.mangaType &&
          ratingAverage == other.ratingAverage &&
          score == other.score &&
          reason == other.reason;
}

class Tag {
  final PlatformInt64 id;
  final String name;

  const Tag({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class TimeOfDayDistribution {
  final PlatformInt64 nightCount;
  final PlatformInt64 morningCount;
  final PlatformInt64 afternoonCount;
  final PlatformInt64 eveningCount;

  const TimeOfDayDistribution({
    required this.nightCount,
    required this.morningCount,
    required this.afternoonCount,
    required this.eveningCount,
  });

  @override
  int get hashCode =>
      nightCount.hashCode ^
      morningCount.hashCode ^
      afternoonCount.hashCode ^
      eveningCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeOfDayDistribution &&
          runtimeType == other.runtimeType &&
          nightCount == other.nightCount &&
          morningCount == other.morningCount &&
          afternoonCount == other.afternoonCount &&
          eveningCount == other.eveningCount;
}

class UserDetailedProfile {
  final PlatformInt64 id;
  final String username;
  final String avatarUrl;
  final String? backgroundUrl;
  final PlatformInt64 gender;
  final String about;
  final PlatformInt64 points;
  final PlatformInt64 loginStreak;
  final String? createdAt;
  final List<String> roles;
  final PlatformInt64? avatarFrameId;
  final PlatformInt64? premiumBackgroundId;

  const UserDetailedProfile({
    required this.id,
    required this.username,
    required this.avatarUrl,
    this.backgroundUrl,
    required this.gender,
    required this.about,
    required this.points,
    required this.loginStreak,
    this.createdAt,
    required this.roles,
    this.avatarFrameId,
    this.premiumBackgroundId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      username.hashCode ^
      avatarUrl.hashCode ^
      backgroundUrl.hashCode ^
      gender.hashCode ^
      about.hashCode ^
      points.hashCode ^
      loginStreak.hashCode ^
      createdAt.hashCode ^
      roles.hashCode ^
      avatarFrameId.hashCode ^
      premiumBackgroundId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserDetailedProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          username == other.username &&
          avatarUrl == other.avatarUrl &&
          backgroundUrl == other.backgroundUrl &&
          gender == other.gender &&
          about == other.about &&
          points == other.points &&
          loginStreak == other.loginStreak &&
          createdAt == other.createdAt &&
          roles == other.roles &&
          avatarFrameId == other.avatarFrameId &&
          premiumBackgroundId == other.premiumBackgroundId;
}

class UserPrivacySettings {
  final PlatformInt64 profileVisibility;
  final PlatformInt64 statisticsVisibility;
  final Int64List statisticsSiteIds;
  final PlatformInt64 previousUsernamesVisibility;

  const UserPrivacySettings({
    required this.profileVisibility,
    required this.statisticsVisibility,
    required this.statisticsSiteIds,
    required this.previousUsernamesVisibility,
  });

  @override
  int get hashCode =>
      profileVisibility.hashCode ^
      statisticsVisibility.hashCode ^
      statisticsSiteIds.hashCode ^
      previousUsernamesVisibility.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserPrivacySettings &&
          runtimeType == other.runtimeType &&
          profileVisibility == other.profileVisibility &&
          statisticsVisibility == other.statisticsVisibility &&
          statisticsSiteIds == other.statisticsSiteIds &&
          previousUsernamesVisibility == other.previousUsernamesVisibility;
}

class UserProfile {
  final PlatformInt64 id;
  final String username;
  final String avatarUrl;
  final String? createdAt;
  final PlatformInt64 loginStreak;

  const UserProfile({
    required this.id,
    required this.username,
    required this.avatarUrl,
    this.createdAt,
    required this.loginStreak,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      username.hashCode ^
      avatarUrl.hashCode ^
      createdAt.hashCode ^
      loginStreak.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          username == other.username &&
          avatarUrl == other.avatarUrl &&
          createdAt == other.createdAt &&
          loginStreak == other.loginStreak;
}
